### ISSUE TITLE
Compile error on lastest version

### ISSUE THREAD

**Issue by crossle** [christophhagen/LibSignalProtocolSwift#3]
update to lastest master branch   
pod 'SignalProtocolSwift', :git => 'https://github.com/christophhagen/SignalProtocolSwift'
pod 'Curve25519', :git => 'https://github.com/christophhagen/Curve25519'

PrivateKey.swift:98:15: Initializer for conditional binding must have Optional type, not 'Data' 
compile error

**Comment by christophhagen** [comment]
I'm in the middle of some updates, seems like it was a temporary error. 

`Curve25519` is now in the Cocoapods trunk, so it should be enough to do: 

```ruby
pod 'SignalProtocolSwift', :git => 'https://github.com/christophhagen/SignalProtocolSwift'
```

Unfortunately there is another pod called SignalProtocolSwift in the cocoapods trunk, so I'll have to think about renaming mine
